# Generated by Django 3.1.5 on 2021-06-13 23:45

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cathegorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('action', 'Action'), ('drama', 'DRAMA'), ('comedy', 'COMEDY'), ('romance', 'ROMANCE')], default='1', max_length=10)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255)),
                ('tag', models.CharField(max_length=100)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('location', models.CharField(max_length=255)),
                ('event_start_date', models.DateField(blank=True, null=True)),
                ('event_start_time', models.TimeField(blank=True, null=True)),
                ('event_end_date', models.DateField(blank=True, null=True)),
                ('event_end_time', models.TimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('images_baniere', models.ImageField(upload_to='img')),
                ('images_2', models.ImageField(upload_to='img')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventss', to='events.cathegorie')),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventss', to='accounts.promotor')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.IntegerField(default=1)),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purche', to='accounts.promotor')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_attende', models.PositiveIntegerField()),
                ('price', models.IntegerField()),
                ('ticket_cathegories', models.CharField(max_length=15)),
                ('slug', models.SlugField(max_length=255)),
                ('ticket_start_date_sell', models.DateField(blank=True, null=True)),
                ('ticket_start_time_sell', models.TimeField(blank=True, null=True)),
                ('ticket_end_date_sell', models.DateField(blank=True, null=True)),
                ('ticket_end_time_sell', models.TimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('min_ticket', models.IntegerField(default=1)),
                ('max_ticket', models.IntegerField(default=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.promotor')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='ShippinrAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.order')),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='accounts.promotor')),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishs', to='events.event')),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishs', to='accounts.promotor')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishs', to='events.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.order')),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderEvents', to='accounts.promotor')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='AchatTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticket_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('Ticket_date_achat', models.DateTimeField(auto_now_add=True)),
                ('Email_customer', models.EmailField(max_length=255, null=True)),
                ('Phone_number', models.CharField(max_length=255, null=True)),
                ('Total_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('Event_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.ticket')),
            ],
        ),
    ]
