# Generated by Django 3.1.5 on 2021-04-01 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tag', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('action', 'Action'), ('drama', 'DRAMA'), ('comedy', 'COMEDY'), ('romance', 'ROMANCE')], default='1', max_length=7)),
                ('description', models.TextField()),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'center': (17.031645, 51.106715), 'style': 'mapbox://styles/mightysharky/cjwgnjzr004bu1dnpw8kzxa72'})),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', mapbox_location_field.models.AddressAutoHiddenField(map_id='map')),
                ('event_start_date', models.DateField(blank=True, null=True)),
                ('event_start_time', models.TimeField(blank=True, null=True)),
                ('event_end_date', models.DateField(blank=True, null=True)),
                ('event_end_time', models.TimeField(blank=True, null=True)),
                ('images_baniere', models.ImageField(upload_to='img')),
                ('images_2', models.ImageField(upload_to='img')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_attende', models.PositiveIntegerField()),
                ('price', models.IntegerField()),
                ('ticket_cathegories', models.CharField(max_length=15)),
                ('ticket_start_date_sell', models.DateField(blank=True, null=True)),
                ('ticket_start_time_sell', models.TimeField(blank=True, null=True)),
                ('ticket_end_date_sell', models.DateField(blank=True, null=True)),
                ('ticket_end_time_sell', models.TimeField(blank=True, null=True)),
                ('min_ticket', models.IntegerField(default=1)),
                ('max_ticket', models.IntegerField(default=10)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
