# Generated by Django 3.1.5 on 2021-06-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish',
            name='event',
        ),
        migrations.RemoveField(
            model_name='publish',
            name='promotor',
        ),
    ]
