# Generated by Django 3.1.5 on 2021-06-14 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210614_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publishs', to='events.ticket'),
        ),
    ]
