# Generated by Django 3.1.5 on 2021-07-19 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0003_auto_20210614_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publ', to='events.event')),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published', to='accounts.promotor')),
            ],
        ),
    ]
