# Generated by Django 3.1.5 on 2021-07-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0004_publishevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_sale_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publi', to='events.event')),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pu', to='accounts.promotor')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tick', to='events.ticket')),
            ],
        ),
    ]
