# Generated by Django 3.1.5 on 2021-07-23 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotor',
            name='amount',
            field=models.IntegerField(blank=True,  max_length=255),
            preserve_default=False,
        ),
    ]
