# Generated by Django 3.1.5 on 2021-01-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nullam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(upload_to='img'),
        ),
    ]
