# Generated by Django 3.1.5 on 2021-03-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nullam', '0004_event_orderevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='orderevent',
            name='user',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='OrderEvent',
        ),
    ]
